### ISSUE TITLE
Broken with Ruby 2.7.0-preview2

### ISSUE THREAD

**Issue by larouxn** [rvm/rubygems-bundler#66]
It seems that this gem is broken when used with [Ruby 2.7.0-preview2](https://www.ruby-lang.org/en/news/2019/10/22/ruby-2-7-0-preview2-released/) on Ubuntu 18.04.
<img width="1440" alt="Screen Shot 2019-10-23 at 08 30 35" src="https://user-images.githubusercontent.com/1557529/67343774-32913f00-f571-11e9-840e-0128e8cda8fd.png">

```
cannot load such file -- rubygems-bundler/noexec
```

Note, we can still run commands with `bundle exec`, as expected.

**Comment by Aqualon** [comment]
The issue is caused by https://github.com/rvm/bundler-unload/blob/master/lib/bundler-unload.rb expecting `Bundler.rubygems` to be one of `Bundler::RubygemsIntegration::[Legacy|Modern|Future]` classes.  Bundler 2.1 does not define those classes anymore, so `Bundler.rubygems.class` is `Bundler::RubygemsIntegration` and therefore the monkeypatch does not work, leading to the error.
